use ethers::contract::Abigen;

fn main() {
    Abigen::new(
        "EmailAuth",
        "../contracts/artifacts/EmailAuth.sol/EmailAuth.json",
    )
    .unwrap()
    .generate()
    .unwrap()
    .write_to_file("./src/abis/email_auth.rs")
    .unwrap();
    Abigen::new(
        "ECDSAOwnedDKIMRegistry",
        "../contracts/artifacts/ECDSAOwnedDKIMRegistry.sol/ECDSAOwnedDKIMRegistry.json",
    )
    .unwrap()
    .generate()
    .unwrap()
    .write_to_file("./src/abis/ecdsa_owned_dkim_registry.rs")
    .unwrap();
    Abigen::new(
        "EmailAccountRecovery",
        "../contracts/artifacts/EmailAccountRecovery.sol/EmailAccountRecovery.json",
    )
    .unwrap()
    .generate()
    .unwrap()
    .write_to_file("./src/abis/email_account_recovery.rs")
    .unwrap();
    Abigen::new(
        "ERC1967Proxy",
        "../contracts/artifacts/ERC1967Proxy.sol/ERC1967Proxy.json",
    )
    .unwrap()
    .generate()
    .unwrap()
    .write_to_file("./tests/erc1967_proxy.rs")
    .unwrap();
    Abigen::new(
        "SimpleWallet",
        "../contracts/artifacts/SimpleWallet.sol/SimpleWallet.json",
    )
    .unwrap()
    .generate()
    .unwrap()
    .write_to_file("./tests/simple_wallet.rs")
    .unwrap();
}
